config/routes.php
<?php
/**
 * Routes configuration.
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * It's loaded within the context of `Application::routes()` method which
 * receives a `RouteBuilder` instance `$routes` as method argument.
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

 use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\Route\DashedRoute;
use Cake\Routing\RouteBuilder;

/*
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 */
/** @var \Cake\Routing\RouteBuilder $routes */
$routes->setRouteClass(DashedRoute::class);

$routes->scope('/', function (RouteBuilder $builder) {
    $builder->registerMiddleware('csrf', new CsrfProtectionMiddleware([
        'httponly' => true,
    ]));
    // $builder->applyMiddleware('csrf');
    /*
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, templates/Pages/home.php)...
     */
    $builder->connect('/', ['controller' => 'Pokemons', 'action' => 'index']);

    /*
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $builder->connect('/pages/*', 'Pages::display');

    /*
     * Connect catchall routes for all controllers.
     *
     * The `fallbacks` method is a shortcut for
     *
     * ```
     * $builder->connect('/:controller', ['action' => 'index']);
     * $builder->connect('/:controller/:action/*', []);
     * ```
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $builder->fallbacks();
});

/*
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * $routes->scope('/api', function (RouteBuilder $builder) {
 *     // No $builder->applyMiddleware() here.
 *     
 *     // Parse specified extensions from URLs
 *     // $builder->setExtensions(['json', 'xml']);
 *     
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Entity/Pokemon.php
<?php
declare(strict_types=1);

namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Pokemon Entity
 *
 * @property int $id
 * @property string $name
 * @property int $height
 * @property int $weight
 * @property string $default_front_sprite_url
 * @property \Cake\I18n\FrozenTime $created
 * @property \Cake\I18n\FrozenTime $modified
 *
 * @property \App\Model\Entity\PokemonStat[] $pokemon_stats
 * @property \App\Model\Entity\PokemonType[] $pokemon_types
 */
class Pokemon extends Entity
{
    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false,
    ];


    /**
     * Undocumented function
     *
     * @return string
     */
    protected function _getMainSprite()
    {
        return $this->default_front_sprite_url ? $this->default_front_sprite_url : 'unknown.png';
    }

    protected function _getBackSprite()
    {
        return $this->default_back_sprite_url ? $this->default_back_sprite_url : 'unknown.png';
    }

    protected function _getShinySprite()
    {
        return $this->front_shiny_sprite_url ? $this->front_shiny_sprite_url : 'unknown.png';
    }

    /**
     * Return the first type for a pokemon
     *
     * @return string
     */
    protected function _getFirstType()
    {
        if (isset($this->pokemon_types) && !empty($this->pokemon_types)) {
            return collection($this->pokemon_types)
                ->extract('type.name')
                ->first();
        }

        return 'normal';
    }

    /**
     * Return the first type for a pokemon
     *
     * @return string
     */
    protected function _getSecondType()
    {
        if (isset($this->pokemon_types) && !empty($this->pokemon_types)) {
            return collection($this->pokemon_types)
                ->extract('type.name')
                ->skip(1)
                ->first();
        }

        return 'normal';
    }

    protected function _getHasSecondType()
    {
        if (isset($this->pokemon_types) && !empty($this->pokemon_types)) {
            return collection($this->pokemon_types)->count() > 1;
        }

        return false;
    }
}

src/Model/Entity/PokemonType.php
<?php
declare(strict_types=1);

namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * PokemonType Entity
 *
 * @property int $id
 * @property string $pokemon_id
 * @property string $type_id
 * @property \Cake\I18n\FrozenTime $created
 * @property \Cake\I18n\FrozenTime $modified
 *
 * @property \App\Model\Entity\Pokemon $pokemon
 * @property \App\Model\Entity\Type $type
 */
class PokemonType extends Entity
{
    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false,
    ];
}

src/Model/Table/PokemonsTable.php
<?php
declare(strict_types=1);

namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Pokemons Model
 *
 * @property \App\Model\Table\PokemonStatsTable&\Cake\ORM\Association\HasMany $PokemonStats
 * @property \App\Model\Table\PokemonTypesTable&\Cake\ORM\Association\HasMany $PokemonTypes
 *
 * @method \App\Model\Entity\Pokemon newEmptyEntity()
 * @method \App\Model\Entity\Pokemon newEntity(array $data, array $options = [])
 * @method \App\Model\Entity\Pokemon[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Pokemon get($primaryKey, $options = [])
 * @method \App\Model\Entity\Pokemon findOrCreate($search, ?callable $callback = null, $options = [])
 * @method \App\Model\Entity\Pokemon patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Pokemon[] patchEntities(iterable $entities, array $data, array $options = [])
 * @method \App\Model\Entity\Pokemon|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Pokemon saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Pokemon[]|\Cake\Datasource\ResultSetInterface|false saveMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\Pokemon[]|\Cake\Datasource\ResultSetInterface saveManyOrFail(iterable $entities, $options = [])
 * @method \App\Model\Entity\Pokemon[]|\Cake\Datasource\ResultSetInterface|false deleteMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\Pokemon[]|\Cake\Datasource\ResultSetInterface deleteManyOrFail(iterable $entities, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class PokemonsTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config): void
    {
        parent::initialize($config);

        $this->setTable('pokemons');
        $this->setDisplayField('name');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->hasMany('PokemonStats', [
            'foreignKey' => 'pokemon_id',
            'saveStrategy' => 'replace',
        ]);
        $this->hasMany('PokemonTypes', [
            'foreignKey' => 'pokemon_id',
            'saveStrategy' => 'replace',
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator): Validator
    {
        $validator
            ->integer('id')
            ->allowEmptyString('id', null, 'create');

        $validator
            ->scalar('name')
            ->maxLength('name', 255)
            ->requirePresence('name', 'create')
            ->notEmptyString('name');

        $validator
            ->integer('height')
            ->requirePresence('height', 'create')
            ->notEmptyString('height');

        $validator
            ->integer('weight')
            ->requirePresence('weight', 'create')
            ->notEmptyString('weight');

        $validator
            ->scalar('default_front_sprite_url')
            ->maxLength('default_front_sprite_url', 255)
            ->allowEmptyString('default_front_sprite_url');
            
        
        $validator
            ->scalar('default_back_sprite_url')
            ->maxLength('default_back_sprite_url', 255)
            ->allowEmptyString('default_back_sprite_url');
        
        $validator
            ->scalar('front_shiny_sprite_url')
            ->maxLength('front_shiny_sprite_url', 255)
            ->allowEmptyString('front_shiny_sprite_url');

        return $validator;
    }

    /**
     * Format Data for save
     *
     * @param array $pokeApiData Data from Poke Api
     * @return array
     */
    public function formatDataForSave($pokeApiData)
    {
        $pokemonStats = $this->PokemonStats->formatDataForSave($pokeApiData['stats']);
        $pokemonTypes = $this->PokemonTypes->formatDataForSave($pokeApiData['types']);

        return [
            'pokedex_number' => $pokeApiData['id'],
            'name' => $pokeApiData['name'],
            'default_front_sprite_url' => $pokeApiData['sprites']['front_default'],
            'height' => $pokeApiData['height'],
            'weight' => $pokeApiData['weight'],
            'pokemon_stats' => $pokemonStats,
            'pokemon_types' => $pokemonTypes,
            'default_back_sprite_url' => $pokeApiData['sprites']['back_default'],
            'front_shiny_sprite_url' => $pokeApiData['sprites']['front_shiny'],
        ];
    }
}

src/Controller/PokemonsController.php
<?php
declare(strict_types=1);

namespace App\Controller;

/**
 * Pokemons Controller
 *
 * @property \App\Model\Table\PokemonsTable $Pokemons
 * @method \App\Model\Entity\Pokemon[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class PokemonsController extends AppController
{
    /**
     * Index method
     *
     * @return \Cake\Http\Response|null|void Renders view
     */
    public function index()
    {
        $this->paginate = [
            'limit' => 30,
        ];

        $pokemons = $this->Pokemons->find('all')->contain(['PokemonStats.Stats', 'PokemonTypes.Types']);
        $pokemons = $this->paginate($pokemons);

        $this->set(compact('pokemons'));
    }

    /**
     * View method
     *
     * @param string|null $id Pokemon id.
     * @return \Cake\Http\Response|null|void Renders view
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $pokemon = $this->Pokemons->get($id, [
            'contain' => ['PokemonStats.Stats', 'PokemonTypes.Types'],
        ]);

        $this->set(compact('pokemon'));
    }

    /**
     * Delete method
     *
     * @param string|null $id Pokemon id.
     * @return \Cake\Http\Response|null|void Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $pokemon = $this->Pokemons->get($id);
        if ($this->Pokemons->delete($pokemon)) {
            $this->Flash->success(__('The pokemon has been deleted.'));
        } else {
            $this->Flash->error(__('The pokemon could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }

    /**
     * Dashboard method
     *
     * @return \Cake\Http\Response|null|void Renders view
     */
    public function dashboard()
    {
        $avgWeight = $this->Pokemons
                    ->find("all")
                    ->where(['id >=' => 387])
                    ->where(['id <=' => 493]);
        $avgWeight = $avgWeight->select(['avg' => $avgWeight->func()->avg('weight')])
                    ->first()
                    ->toArray();
        $this->set(Array('avgWeight'=> $avgWeight['avg']));

        $fairyPokemonsGeneration1 = $this->Pokemons->find("all")
                                ->join([
                                    'pokemon_types' => [
                                        'table' => 'pokemon_types',
                                        'conditions' => 'pokemons.id = pokemon_types.pokemon_id',
                                    ]]);
        $fairyPokemonsGeneration3 = clone $fairyPokemonsGeneration1;
        $fairyPokemonsGeneration7 = clone $fairyPokemonsGeneration1;
        $fairyPokemonsGeneration1->where(["type_id =" => 10])->where(['pokemons.id <=' => 151]);
        $fairyPokemonsGeneration3->where(["type_id =" => 10])->where(['pokemons.id >=' => 252])->where(['pokemons.id <=' => 386]);
        $fairyPokemonsGeneration7->where(["type_id =" => 10])->where(['pokemons.id >=' => 722])->where(['pokemons.id <=' => 809]);
        $fairyPokemonsGeneration1 = $fairyPokemonsGeneration1->select(['count' => $fairyPokemonsGeneration1->func()->count('pokemons.id')])
                                ->first()
                                ->toArray();
        $fairyPokemonsGeneration3 = $fairyPokemonsGeneration3->select(['count' => $fairyPokemonsGeneration3->func()->count('pokemons.id')])
                                ->first()
                                ->toArray();
        $fairyPokemonsGeneration7 = $fairyPokemonsGeneration7->select(['count' => $fairyPokemonsGeneration7->func()->count('pokemons.id')])
                                ->first()
                                ->toArray();
        $this->set(Array('fairyPokemonsGeneration1'=> $fairyPokemonsGeneration1['count']));
        $this->set(Array('fairyPokemonsGeneration3'=> $fairyPokemonsGeneration3['count']));
        $this->set(Array('fairyPokemonsGeneration7'=> $fairyPokemonsGeneration7['count']));

        $fastestsPokemons = $this->Pokemons->find("all")
                            ->join([
                                'pokemon_stats' => [
                                    'table' => 'pokemon_stats',
                                    'type' => 'inner',
                                    'conditions' => 'pokemons.id = pokemon_stats.pokemon_id',
                                ]])
                            ->select(['name'])
                            ->select(['pokemon_stats.value'])
                            ->where(['stat_id = ' => 6])
                            ->order(['value' => 'DESC'])
                            ->limit(10)
                            ->toArray();
        $this->set(compact('fastestsPokemons'));
    }
}

templates/Pokemons/dashboard.php
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Pokemon[]|\Cake\Collection\CollectionInterface $pokemons
 */
?>
<div class="content">
    <h3><?= __('Dashboard') ?></h3>
    <div class="mb-3 bold">
        <h4 class="text-center text-underline ">Average weight of 4th generation pokemon : <?= $avgWeight ?>hg</h4>
    </div>
    <h4 class="text-center mt-5">Number of Fairy-type Pokemon per generation</h4>
    <table class="table">
        <thead class="thead-dark text-center">
            <tr>
            <th class="text-center" scope="col">Generation</th>
            <th class="text-center" scope="col">Number of Fairy-type Pokemon</th>
            </tr>
        </thead>
        <tbody>
            <tr>
            <th class="text-center" scope="row">1</th>
            <td class="text-center"><?= $fairyPokemonsGeneration1 ?></td>
            </tr>
            <tr>
            <th class="text-center" scope="row">3</th>
            <td class="text-center"><?= $fairyPokemonsGeneration3 ?></td>
            </tr>
            <tr>
            <th class="text-center" scope="row">7</th>
            <td class="text-center"><?= $fairyPokemonsGeneration7 ?></td>
            </tr>
        </tbody>
    </table>
    <h4 class="text-center mt-5">Fastests pokemons</h4>
    <table class="table">
        <thead class="thead-dark">
            <tr>
            <th class="text-center" scope="col">#</th>
            <th class="text-center" scope="col">Pokemon</th>
            <th class="text-center" scope="col">Speed</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($fastestsPokemons as $key=>$pokemon): ?>
                <tr>
                <th class="text-center" scope="row"><?=$key+1 ?></th>
                <td class="text-center"><?= $pokemon['name'] ?></td>
                <td class="text-center"><?= $pokemon['pokemon_stats']['value'] ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

templates/Pokemons/index.php
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Pokemon[]|\Cake\Collection\CollectionInterface $pokemons
 */
?>
<div class="pokemons index content">
    <h3><?= __('Pokemons') ?></h3>

    <div class="row">
        <?php foreach ($pokemons as $pokemon) : ?>
                <div class="col-12 col-md-4 col-sm-6 col-xs-12">
                    <?= $this->element('Pokemons/card', ['pokemon' => $pokemon]); ?>
                </div>
        <?php endforeach; ?>
    </div>
    <div class="paginator">
        <ul class="pagination">
            <?= $this->Paginator->first('<< ' . __('first')) ?>
            <?= $this->Paginator->prev('< ' . __('previous')) ?>
            <?= $this->Paginator->numbers() ?>
            <?= $this->Paginator->next(__('next') . ' >') ?>
            <?= $this->Paginator->last(__('last') . ' >>') ?>
        </ul>
        <p><?= $this->Paginator->counter(__('Page {{page}} of {{pages}}, showing {{current}} record(s) out of {{count}} total')) ?></p>
    </div>
</div>

templates/Pokemons/view.php
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Pokemon $pokemon
 */
?>

<body>
    <div class="content">
        <h3><?= __('View') ?></h3>
        <div class="row">
            <div class="col-md-6 row justify-content-center align-self-center row">
                <?= $this->Html->image($pokemon->main_sprite); ?>
            </div>
            <div class="col-md-6">
                <h1 class="card__name" style="font-size:60px;"><?= h($pokemon->name) ?></h1>
                <div class="row mt-3">
                    <div class="col-md-6">
                        <h5 class="card_type card__type <?= $pokemon->first_type ?> card--<?= $pokemon->first_type ?>"><?= $pokemon->first_type ?></h5>
                    </div>
                    <?php if(!empty($pokemon->second_type)) : ?>
                        <div class="col-md-6">
                            <h5 class="card__second_type <?= $pokemon->second_type ?>"><?= $pokemon->second_type ?></h5>                  
                        </div>
                    <?php endif; ?>
                    <div class="table-responsive">
                        <table class="card__stats my-5">
                            <tbody>
                                <?php $combine = array_combine(array("HP","Defense","Attack","Special Attack", "Special Defense","Speed"),$pokemon->pokemon_stats) ?>
                                <?php foreach($combine as $name => $pokemonStats): ?>
                                    <tr>
                                        <td class="text-center text-light card--<?= $pokemon->first_type ?>" scope="row"><?= $name ?></td>
                                        <td class="text-center"><?= $pokemonStats->value ?></td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="row my-5">
            <div id="carouselExampleControls" class="carousel slide w-50 mx-auto" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active text-center">
                        <div><?= $this->Html->image($pokemon->main_sprite); ?>
                        <h2 class="card__name">Front</h2>
                        </div>
                    </div>
                    <div class="carousel-item text-center">
                        <?= $this->Html->image($pokemon->back_sprite); ?>
                        <h2 class="card__name">Back</h2>
                    </div>
                    <div class="carousel-item text-center">
                        <?= $this->Html->image($pokemon->shiny_sprite); ?>
                        <h2 class="card__name">Shiny</h2>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                    <span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="#000000" class="bi bi-arrow-left" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
                        </svg></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                    <span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="#000000" class="bi bi-arrow-right" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"/>
                        </svg></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>

    <!--Scripts for the carousel -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>